# ruff.toml - Configuration for the Ruff linter and formatter

# Line length configuration
line-length = 120

# Enable all recommended rules by default
lint.select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "W",   # pycodestyle warnings
]

# Ignore specific rules
#lint.ignore = [
#    "E203",  # Whitespace before ':' (conflicts with black)
#    "E501",  # Line too long (handled by formatter)
#    "B905",  # `zip()` without an explicit `strict=` parameter (requires Python 3.10+)
#]


# Exclude certain directories and files
exclude = [
    ".git",
]

# Automatically fix violations where possible
fix = true
show-fixes = true

# Formatter configuration
[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
