name: Build LaTeX PDF

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile LaTeX with Tectonic

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Tectonic
        working-directory: paper
        run: |
          curl --proto '=https' --tlsv1.2 -fsSL https://drop-sh.fullyjustified.net | sh
          ./tectonic --version

      - name: Create header.txt
        working-directory: paper
        run: |
          touch header.txt

          echo "Repo: ${{ github.repository }}" >> header.txt
          echo "Version: ${{ github.event.inputs.tag }}" >> header.txt
          echo "Date: $(date '+%d %B %Y')" >> header.txt

          # display the header.txt file
          cat header.txt

      - name: Compile LaTeX document
        working-directory: paper
        run: |
          mkdir -p compiled
          cat header.txt
          ./tectonic document.tex --outdir compiled --keep-logs --keep-intermediates

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: paper/compiled/document.pdf
