name: Build LaTeX PDF

on:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile LaTeX with Tectonic

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Create header.txt
        working-directory: paper
        run: |
          rm -f header.tex

          SHA=$(git rev-parse --short HEAD)
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          REPO=$(basename -s .git `git config --get remote.origin.url`)

          # Write header.tex directly with LaTeX-safe wrapper
          echo "\\texttt{Repo: $REPO, Branch: $BRANCH, Version: $SHA}" > header.tex

          # display the header.tex file
          cat header.tex

      - name: Compile LateX
        uses: tschm/cradle/actions/latex@main
        with:
          tex-file: document.tex
          tex-folder: paper
          #target-branch: draft

      - name: Check folder with compiled document
        run: |
          ls paper/compiled

      - name: Upload compiled PDF
        uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: paper/compiled/*.pdf
