name: Build LaTeX PDF

on:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile LaTeX with Tectonic

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create header.txt
        working-directory: paper
        run: |
          rm header.txt
          SHA=$(git describe --tags --dirty --always)
          echo "Repo: ${{ github.repository }}, Version: $SHA" > header.txt

          # display the header.txt file
          cat header.txt

      - name: Compile LateX
        uses: tschm/cradle/actions/latex@main
        with:
          tex-file: document.tex
          tex-folder: paper
          #target-branch: draft

      - name: Check folder with compiled document
        run: |
          ls paper/compiled
