name: Build LaTeX PDF

on:
  push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile LaTeX with Tectonic

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      #- name: Install biber
      #  run: |
      #    sudo apt-get update
      #    sudo apt-get install -y biber
      #    echo "Installed Biber:"
      #    biber --version

      - name: Install Tectonic
        working-directory: paper
        run: |
          curl --proto '=https' --tlsv1.2 -fsSL https://drop-sh.fullyjustified.net | sh
          echo "Installed Tectonic:"
          ./tectonic --version

      - name: Create header.txt
        working-directory: paper
        run: |
          touch header.txt

      - name: Compile LaTeX document
        working-directory: paper
        run: |
          mkdir -p compiled
          cat header.txt
          ./tectonic document.tex --outdir compiled --keep-logs --keep-intermediates

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: paper/compiled/document.pdf

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: "draft"
          folder: paper/**/*.pdf
          commit-message: "Compiled paper"
          clean: true
          single-commit: false
