name: Build LaTeX PDF

on:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile LaTeX with Tectonic

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LateX
        uses: tschm/cradle/actions/latex@main
        with:
          tex-file: document.tex
          tex-folder: paper
          target-branch: draft
