# Workflow to build and publish LaTeX documents
# This workflow runs automatically on every push to the repository

name: LATEX

on:
  push  # Trigger on push events

# Permissions needed for the workflow
permissions:
  contents: write  # Allows the workflow to write to the repository (for draft branch)

jobs:
  # Job to build and publish the LaTeX document
  latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4  # Check out the repository code


      - name: Create header.txt
        run: |
          touch paper/header.txt

          echo "Repo: ${{ github.repository }}\n" >> paper/header.txt
          echo "Version: $(git describe --tags --always --dirty)\n" >> paper/header.txt
          echo "Date: $(date '+%d %B %Y')\n" >> paper/header.txt

          # display the header.txt file
          cat paper/header.txt

      - name: "Build and publish the LaTeX document"
        uses: ./actions/latex  # Custom action to build LaTeX documents
        with:
          paper: paper/document.tex  # Path to the LaTeX document to build
