name: Build LaTeX Document

on:
  workflow_call:
    outputs:
      pdf_path:
        description: "Path to the compiled PDF files"
        value: ${{ jobs.build-latex.outputs.pdf_path }}

jobs:
  build-latex:
    runs-on: ubuntu-latest
    name: Compile LaTeX Document
    outputs:
      pdf_path: "paper/compiled"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Run make_header.sh
        run: |
          ./make_header.sh
          cat header.tex
          cp header.tex paper/header.tex
          cat paper/header.tex

      - name: Compile LaTeX
        uses: tschm/cradle/actions/latex@v0.3.06
        with:
          tex-file: document.tex
          tex-folder: paper

      - name: Upload compiled PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: latex-build-artifact
          path: paper/compiled/*.pdf
