name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.2.3)'
        required: true
        type: string

  push:
    tags:
      - 'v*'  # Trigger only on tags like v1.2.3

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  tagging:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - name: Create and Push Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "${{ github.event.inputs.tag }}" -m "Release ${{ github.event.inputs.tag }}"
          git push origin "${{ github.event.inputs.tag }}"

  latex:
    runs-on: ubuntu-latest
    needs: [tagging]

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Run make_header.sh
        run: |
          ./make_header.sh
          cat header.tex
          cp header.tex paper/header.tex
          cat paper/header.tex

      - name: Compile LaTeX
        uses: tschm/cradle/actions/latex@v0.3.06
        with:
          tex-file: document.tex
          tex-folder: paper

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2.3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.TAG }}
          generate_release_notes: true
          files: paper/compiled/*.pdf

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: paper/compiled

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
